package enum

type VERIFICATIONTYPE string

const (
	INITIAL    VERIFICATIONTYPE = "INTIIAL"
	PREPREPARE VERIFICATIONTYPE = "PREPREPARE"
	PREPARE    VERIFICATIONTYPE = "PREPARE"
	COMMIT     VERIFICATIONTYPE = "COMMIT"
	EXECUTE    VERIFICATIONTYPE = "EXECUTE"
)
